arm_rt_server:
  ros__parameters:
    arm_planning_group: "interbotix_arm"

    position_err_tolerance_meters: 0.01
    velocity_err_tolerance_meters: 0.05
    angular_err_tolerance_radians: 0.0349 # ~ 2 deg

    update_freq: 60 # Hz
